const info = [
  {
    id: 1,
    price: 1,
    name: "Project Arabella",
    houseprice: "1 million house",
    profile: "../public/photos/image2.jpg",
  },
  {
    id: 2,
    price: 1,
    name: "Project Arabella",
    houseprice: "1 million house",
    profile: "../public/photos/image2.jpg",
  },
  {
    id: 3,
    price: 1,
    name: "Project Arabella",
    houseprice: "1 million house",
    profile: "../public/photos/image2.jpg",
  },
  {
    id: 4,
    price: 2,
    name: "Project Arylla",
    houseprice: "2 million house",
    profile: "../public/photos/image3.jpg",
  },
  {
    id: 5,
    price: 2,
    name: "Project Arylla",
    houseprice: "2 million house",
    profile: "../public/photos/image3.jpg",
  },
  {
    id: 6,
    price: 2,
    name: "Project Arylla",
    houseprice: "2 million house",
    profile: "../public/photos/image3.jpg",
  },
  {
    id: 7,
    price: 2,
    name: "Project Arylla",
    houseprice: "2 million house",
    profile: "../public/photos/image3.jpg",
  },
  {
    id: 8,
    price: 3,
    name: "Project Carmella",
    houseprice: "3 million house",
    profile: "../public/photos/image4.jpg",
  },
  {
    id: 9,
    price: 3,
    name: "Project Carmella",
    houseprice: "3 million house",
    profile: "../public/photos/image4.jpg",
  },
];
export default info;
